name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # This should match the output folder from your build step
          branch: gh-pages # The branch to which the site will be deployed
          clean: true # Optionally clean the target branch before deploying
          token: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token to authorize the deployment