name: Manual Deployment Workflow

# This workflow will only run when manually triggered via the GitHub Actions interface
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (e.g., staging, production)'
        required: true
        default: 'staging'
      image_tag:
        description: 'Tag of the image to deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Amazon ECS
        run: |
          echo "Deploying to environment: ${{ github.event.inputs.environment }}"
          echo "Deploying image tag: ${{ github.event.inputs.image_tag }}"
          # Here you would add the command to deploy the specific image tag to ECS
          # For example, using AWS CLI:
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }} \
            --task-definition ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ github.event.inputs.image_tag }}
